version: '3.4'

networks:
  lan:

services:
  mysql:
    image: mysql:5.7
    hostname: localhost
    networks:
      - lan
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=totalizator_db_schema